version: '3.8'

services:
  nginx-alpine:
    container_name: nginx-alpine
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/http.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static_pages:/var/www
