FROM alpine:3.19.1

RUN apk add nginx --no-cache
#&& \
#	mkdir /www

#COPY ./nginx/nginx.conf /etc/nginx/http.d/default.conf
#COPY ./static_pages/index.html /www/

#CMD ["nginx", "-g", "daemon off;"]
