version: "3.9"

services:
  realworld-app:
    image: realworld-app:1.0.0
    container_name: realworld-app 
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - realworld-app-network
    depends_on:
      - db 

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data 
    networks:
      - realworld-app-network


networks:
  realworld-app-network:
    driver: bridge
    name: "realworld-app-network"
