-d C:\Users\Pavel\Desktop\Leti\FPGA\lab_2\impl\gwsynthesis\lab_2.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\Pavel\Desktop\Leti\FPGA\lab_2\src\lab_2.cst
-cfg C:\Users\Pavel\Desktop\Leti\FPGA\lab_2\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
