// File: led_blinker.v
// Generated by MyHDL 0.11
// Date: Wed Dec  6 17:52:04 2023


`timescale 1ns/10ps

module led_blinker (
    input,
    led
);


input input;
output led;
reg led;




always @(input) begin: LED_BLINKER_ON_OFF_LED
    if ((input == 1)) begin
        led = 1;
    end
    else begin
        led = 0;
    end
end

endmodule
