#!/bin/bash

# проверка наличия переданного аргумента
if [ $# -lt 1 ]
then
	echo $0: error: File not specified
else	
	# получение inode
	inode=$(ls -i $1 | cut -d ' ' -f 1)
	
	# поиск жестких ссылок
	echo $(ls -l -R -i /home/alex | grep $inode)
fi
