#!/bin/bash

# сохраняем стартовый размер директории
size=$(du -hs $1)
echo "Current dir size: $size"
tmp_size=$(du -hs $1 | cut -c 1-3)

# в цикле создаем файлы и директории
for i in {1..250}
do	
	#создаем файл и директорию
	file_name=$1/$i.txt
	> $file_name
	
	echo "some text" >> $file_name
	mkdir $1/$i
	
	# подсичтываем изменение размера директории
	cur_size=$(du -hs $1 | cut -c 1-3)
	let "df=$cur_size - $tmp_size"
	tmp_size=$(du -hs $1 | cut -c 1-3)
	
	# вывод скачка
	if [ df > 4 ]
	then
		echo "$cur_size size jump $df"
	fi
	
done

# вывод текущего размера директории после добавления файлов и папок
tmp_size=$(du -hs $1)
echo "Current dir size: $tmp_size"

# удаление папок и файлов
for i in {130..230}
do
	file_name=$1/$i.txt
	rm -rf $file_name $1/$i
done

# вывод конечного размера директории
end_size=$(du -hs $1)
echo "Current dir size: $end_size" 



