#!/bin/bash

# все типы файлов
file_types='- c d l s b p'

# цикл по всем типам файлов
for i in $file_types
do	
	
	echo "file type: $i"
	
	# запись первого примера
	file_search=$(ls -l -R $1 | grep ^$i | head -1)
	
	# проверка на наличие файла нужного типа
	if [[ -n $file_search ]]
	then
		echo "$file_search"
	else
		echo "not found"
	fi
done
