[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "algorithmic_phase_transition"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
]
authors = [
  { name="Shavrin Aleksei Pavlovitch", email="alex.shavrin200303@gmail.com" },
]
description = ""
readme = "README.md"
keywords = ["phase transition", "NP"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
