stages:
  - build


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


# build_mysql:
#   stage: build
#   image: docker:stable
#   services:
#     - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#   script:
#     - docker pull mysql:8.3 #-t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    
#     # rule for master branch
#     - if [[ ${CI_COMMIT_BRANCH} == ${CI_DEFAULT_BRANCH} ]]; then
#       docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}:latest; 
#       docker push ${CI_REGISTRY_IMAGE}:latest;
#     fi
    
#     # rule for tags
#     - if [[ -z ${CI_COMMIT_TAG} ]]; then
#       docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG};
#     else
#       docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}; 
#       docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG};
#     fi
#   rules:
#     - exists:
#         - ./React-Spring-App-DevOps/spring-backend/.env
#       changes:
#         - ./React-Spring-App-DevOps/spring-backend/.env
#       when: always
#   tags:
#     - docker


build_spring-back:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:${CI_COMMIT_REF_SLUG} ./React-Spring-App-DevOps/spring-backend
    
    # rule for master branch
    - if [[ ${CI_COMMIT_BRANCH} == ${CI_DEFAULT_BRANCH} ]]; then
      docker tag ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:latest; 
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:latest;
    fi
    
    # rule for tags
    - if [[ -z ${CI_COMMIT_TAG} ]]; then
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:${CI_COMMIT_REF_SLUG};
    else
      docker tag ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:${CI_COMMIT_TAG}; 
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/spring-backend:${CI_COMMIT_TAG};
    fi
  rules:
    - exists:
        - ./React-Spring-App-DevOps/spring-backend/Dockerfile
      changes:
        - ./React-Spring-App-DevOps/spring-backend/*
      when: always
  tags:
    - docker


build_react-front:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:${CI_COMMIT_REF_SLUG} ./React-Spring-App-DevOps/react-frontend
    
    # rule for master branch
    - if [[ ${CI_COMMIT_BRANCH} == ${CI_DEFAULT_BRANCH} ]]; then
      docker tag ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:latest; 
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:latest;
    fi
    
    # rule for tags
    - if [[ -z ${CI_COMMIT_TAG} ]]; then
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:${CI_COMMIT_REF_SLUG};
    else
      docker tag ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:${CI_COMMIT_TAG}; 
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/react-frontend:${CI_COMMIT_TAG};
    fi
  rules:
    - exists:
        - ./React-Spring-App-DevOps/react-frontend/Dockerfile
      changes:
        - ./React-Spring-App-DevOps/react-frontend/*
      when: always
  tags:
    - docker


build_nginx-proxy:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:${CI_COMMIT_REF_SLUG} ./React-Spring-App-DevOps/nginx-proxy

    # rule for master branch
    - if [[ ${CI_COMMIT_BRANCH} == ${CI_DEFAULT_BRANCH} ]]; then
      docker tag ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:latest; 
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:latest;
    fi
    
    # rule for tags
    - if [[ -z ${CI_COMMIT_TAG} ]]; then
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:${CI_COMMIT_REF_SLUG};
    else
      docker tag ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:${CI_COMMIT_TAG}; 
      docker push ${CI_REGISTRY_IMAGE}/React-Spring-App-DevOps/nginx-proxy:${CI_COMMIT_TAG};
    fi
  rules:
    - exists:
        - ./React-Spring-App-DevOps/nginx-proxy/Dockerfile
      changes:
        - ./React-Spring-App-DevOps/nginx-proxy/*
      when: always
  tags:
    - docker
