include:
  - project: 'leti2080117/DevOps/lab6_ci'
    ref: test
    file: 'docker-build.yml'

stages:
  - build

build backend:
  variables:
    DOCKERDIR: "React-Spring-App-DevOps/spring-backend"
    IMAGE_ID: "spring-backend"
  extends:
    - .docker_build_dind
  only:
    changes:
      - "React-Spring-App-DevOps/spring-backend/**/*"
  
build frontend:
  variables:
    DOCKERDIR: "React-Spring-App-DevOps/react-frontend"
    IMAGE_ID: "react-frontend"
  extends:
    - .docker_build_dind
  only:
    changes:
      - "React-Spring-App-DevOps/react-frontend/**/*"

build proxy:
  variables:
    DOCKERDIR: "React-Spring-App-DevOps/nginx-proxy"
    IMAGE_ID: "nginx-proxy"
  extends:
    - .docker_build_dind
  only:
    changes:
      - "React-Spring-App-DevOps/nginx-proxy/**/*"