.docker_login: &docker-login
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin $REGISTRY

.docker_build: &docker-build
  - if [[ "$CI_COMMIT_REF_SLUG" == "main" ]]; then
      IMAGE_TAG="latest"; 
    fi
  - docker build
    -f ${DOCKERDIR}/${DOCKERFILE}
    -t ${CI_REGISTRY_IMAGE}/${IMAGE_ID}:${IMAGE_TAG} ${DOCKERDIR}

.docker_push: &docker-push
  - *docker-login
  - if [[ ! -z "${CI_COMMIT_TAG}" ]]; then
      IMAGE_TAG="$CI_COMMMIT_TAG";
    fi
  - if [[ "$CI_COMMIT_REF_SLUG" == "main" ]]; then
      IMAGE_TAG="latest"; 
    fi
  - docker push ${CI_REGISTRY_IMAGE}/${IMAGE_ID}:${IMAGE_TAG}

.docker_build_dind:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE_ID: ""
    DOCKERDIR: "."
    DOCKERFILE: "Dockerfile"
    REGISTRY: ${CI_REGISTRY}
    REGISTRY_USER: ${CI_REGISTRY_USER}
    REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}
    IMAGE_TAG: ${CI_COMMIT_REF_SLUG}
    IMAGE_PATH: ''
    DOCKER_HOST: tcp://docker:2375
  script:
    - *docker-login
    - *docker-build
    - *docker-push
  tags:
    - docker

